spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-app?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/spring-app?serverTimezone=Europe/Moscow&useSSL=false
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: +12693715337

jwt:
  token:
    secret: jwtsecret
    expired: 3600000