spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-app?serverTimezone=Europe/Moscow&useSSL=false
    username: root
    password: root
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/spring-app?serverTimezone=Europe/Moscow&useSSL=false
twilio:
  account-sid: ACaf1b556ac9d61456464cb6d42174efd5
  auth-token: eb1653174e4fb8ce65a450d37c94a656
  phone-number: +12693715337