spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/spring_app?serverTimezone=Europe/Moscow&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    hikari:
      maximum-pool-size: 1
    tomcat:
      max-active: 2
      initial-size: 1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    user: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/spring_app?serverTimezone=Europe/Moscow&useSSL=false}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: +12693715337

jwt:
  token:
    secret: jwtsecret
    expired: 3600000

